### ISSUE TITLE
Enhancement : Generate less http traffic

### ISSUE THREAD

**Issue by mgodlewski** [timoschwarzer/gitlab-monitor#112]
I'm using the gitlab-monitor but I feel it generates lots of http traffic.
I'm following 5 projects, with a pollingIntervalMultiplier: 5.0

After 30 minutes, it's more thant 4000 requests dans 30 Mo of transferred data :
![latest-screenshot](https://user-images.githubusercontent.com/5939318/67205848-e29b6680-f410-11e9-800c-f90916ba366f.png)

I see lors of requests to /pipelines.

Perhaps the logic coul be reworked to get only latest pipeline on every branch/tag ?
The default polling intervals seems very low (I guess my figure should be x5 with the default pollingIntervalMultiplier).

**Comment by timoschwarzer** [comment]
In my opinion the current `pollingIntervalMultiplier` is already a compromise between request count and real time updates. I don't want to set the multiplier way higher because this is a real time dashboard and it makes no sense to me to display a 15 seconds long failed pipeline minutes after it actually failed.
