### ISSUE TITLE
Filter by branch/master OR show branches as separate sections

### ISSUE THREAD

**Issue by araneforseti** [timoschwarzer/gitlab-monitor#18]
It would be useful to have the option to filter by a particular branch or to show all branches at once.

For instance, right now we have some development super active on a branch, so the build monitor is almost always showing that branch, but most of the team only needs to know if master is active and that branch being red isn't useful information for them.

**Comment by timoschwarzer** [comment]
Thank you for opening this issue 😅

My proposal: Have a config.json somewhere that defines whether the monitor should show just one branch or all branches.

**Comment by timoschwarzer** [comment]
I'm even thinking of putting all configuration but the API token in a file...

**Comment by krokodyl1220** [comment]
Hi Timo, 

How are the things going with this issue? This is basically the only thing that is keeping us from using this project in our dev rooms and moving fully to gitlab CI, since it is one of the only gitlab monitoring tools that acts similar to Jenkins dashboard plugin (https://wiki.jenkins.io/display/JENKINS/Build+Monitor+Plugin). Right now the dashboard thing is the only issue for us, sine we depend on it heavily in our daily workflow.

Just displaying all of the branches together with the latest build on the branch is the behaviour we are after.

I dabbled a bit in a code and have an idea on how to try to solve the problem, but since I am no coder, my approach may be totally wrong, so before spending a lot of my time (that most probably will no yield any results at all) I wanted to get in touch and check with you.

**Comment by timoschwarzer** [comment]
Hi @krokodyl1220 
I'll roll out a new version tomorrow that has more configuration options, including this one. :)

**Comment by krokodyl1220** [comment]
Oh my, that is fantastic news. Thank you for the reply and great work. :D

**Comment by timoschwarzer** [comment]
Whoop whoop! I worked the entire weekend to remake the configuration and add some features.
You can find the new release and instructions here: https://github.com/timoschwarzer/gitlab-monitor/releases/tag/1.7

I think I've met your requirements @araneforseti @krokodyl1220, so I'll close this issue for now. If there's missing something, please reopen this issue and comment on what's wrong ;)
