### ISSUE TITLE
config.json security issue

### ISSUE THREAD

**Issue by thespamer** [timoschwarzer/gitlab-monitor#189]
the http://url/config.json is readable by browser..

Is there some way to run this as server side instead of a browser side?

In that way, we can hide the config.json token value.

Regards ;-)

**Comment by timoschwarzer** [comment]
Hi!

The configuration file needs to be readable by the browser, because gitlab-monitor runs entirely in the browser. It does not have a server.

The config file is intended for isolated environments (e.g. IT departments with their own isolated network).

If you don't want the token to be in the config file, you need to configure gitlab-monitor using the default method (bottom left corner → Configure)
