### ISSUE TITLE
Wrong branch names are displayed (always Master branch)

### ISSUE THREAD

**Issue by aponski** [timoschwarzer/gitlab-monitor#22]
Hi, 

My pipelines are triggered when tag is added to gitlab. Pipeline is started on master or develop branch but on monitoring dashboard branch master i always shown.

**Comment by timoschwarzer** [comment]
Hi! :)

Currently, gitlab-monitor does only show the default branch. There's definitely room for improvements there.

**Comment by raine** [comment]
:+1: Fixing this would be great

**Comment by bonndan** [comment]
I have a running dashboard (can't show whole screenshot since it is private) showing branch names or tags on the cards. In pipeline.vue you can see the pipeline.ref property is accessed, which is correct. Please check you ajax network request for pipeline data to contain correct branch names. Maybe GitLab is the problem?

![tag](https://user-images.githubusercontent.com/143695/43955664-842dd4c4-9ca1-11e8-95b4-ea888ca5ae2c.png)

**Comment by timoschwarzer** [comment]
Oh, I just realized I haven't updated the hosted version in a while. Sorry for that! It should be up-to-date now. :sweat_smile: 

@aponski Please check if it shows the correct branch name for you now.

**Comment by aponski** [comment]
It's ok now, thanks @timoschwarzer
