### ISSUE TITLE
Token shouldn't be passed via GET variable

### ISSUE THREAD

**Issue by DailenG** [timoschwarzer/gitlab-monitor#24]
Hey, just found this project and love it! I'm working on some ideas to customize it and tweak it but had one thing I wanted to add as an issue. Passing a full access token as a GET variable I think is an accident waiting to happen!

An API token being passed as a GET variable is susceptible to being grabbed or snagged by all sorts of things

- Previous page URL can be grabbed by javascript
- URL can be viewed in the history (even via CLI)
- Open hotspots where someone nearby is sniffing traffic
- Router/Firewall logs
- etc

There have been cases, albeit rare, of code repositories being compromised and code being injected with malware. Corporate espionage cases of companies stealing competitors software. Holding source code for ransom not to publicly release. 

Passing info via get vars is cool but you wouldn't ask someone to include a password in the URL. I would have a field that lets someone enter the token in a form field, hit submit, and keep it in a post variable or cookie.

**Comment by timoschwarzer** [comment]
Hi there! :)

You are right, tokens should not be passed as query parameters. But just for you information: When you use HTTPS, the only bottleneck will be the browser history and the server logs as query parameters are transport encrypted. If you use the hosted version at my website, it's just the browser history because I don't log URLs for that application.

There has been the idea to move the configuration to an extra file (e.g. config.json) and pass the path to that file as a query parameter. I just haven't had time to implement this and this would be happy to see a PR. :)

**Comment by bonndan** [comment]
Since you provide a docker image you might consider reading the gitlab api and private token from environment variables. In terms of security it's even worse, but setup is much easier for teams.

**Comment by DailenG** [comment]
@timoschwarzer Actually in a lot of business environments high end firewalls are scanning SSL traffic. https://www.sonicwall.com/en-us/support/knowledge-base/170505782716496 so everything gets logged and scanned creating quite a trail. 

I'm actually working on an version that will walk you through generating a SSH key connection.

**Comment by timoschwarzer** [comment]
@DailenG What do you think of prompting the user and saving the token to `localStorage`?

**Comment by timoschwarzer** [comment]
Whoop whoop! I worked the entire weekend to remake the configuration and add some features.
You can find the new release and instructions here: https://github.com/timoschwarzer/gitlab-monitor/releases/tag/1.7

I'll close this issue as the token is no longer passed as GET parameter.
